### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by hissssst** [andrzej-mag/meshx#1]
What is a current status of this project?
Will there be any tests or CI?

**Comment by andrzej-mag** [comment]
Meshx project is being actively developed / WIP.

[Meshx](https://github.com/andrzej-mag/meshx) package defines [service mesh adapter behavior](https://github.com/andrzej-mag/meshx/blob/master/lib/meshx_service_mesh.ex) only, so there are no tests.

Other Meshx packages have already some tests, check for example [MeshxRpc tests](https://github.com/andrzej-mag/meshx_rpc/tree/master/test) or [MeshxConsul tests](https://github.com/andrzej-mag/meshx_consul/tree/master/test). Tests for [MeshxNode](https://github.com/andrzej-mag/meshx_node) are pending: it is possible that MeshxNode will be completely rewritten.

**Comment by hissssst** [comment]
Great!

I think it worths mentioning project status in README
